global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['api-gateway.railway.internal:8080', 'authentication-service.railway.internal:8080', 'user-service.railway.internal:8080', 'map-service.railway.internal:8080', 'notification-service.railway.internal:8080', 'contact-service.railway.internal:8080']